### ISSUE TITLE
Hi, I'm the most beautiful girl in the world

### ISSUE THREAD

**Issue by zxc0328** [misakar/GFWanted#1]
May I have your QQ number?

**Comment by misakar** [comment]
Please give me your photo,Thanks.

**Comment by zxc0328** [comment]
![photo](http://7oxh2b.com1.z0.glb.clouddn.com/Screen%20Shot%202016-02-28%20at%2011.10.30%20PM.png)

**Comment by lujun9972** [comment]
It seems you are the funniest guy in the world…
